export const PLIST_ADD_POINT = 'PLIST_ADD_POINT';
export const PLIST_DEL_POINT = 'PLIST_DEL_POINT';
export const PLIST_DEL_ALL_POINTS = 'PLIST_DEL_ALL_POINTS';
export const PLIST_REORDER_LIST = 'PLIST_REORDER_LIST';
